### ISSUE TITLE
能否支持对Tags重命名？

### ISSUE THREAD

**Issue by Vstory** [zenghongtu/Remu#13]
能否支持对Tags重命名？

**Comment by zenghongtu** [comment]
支持的，鼠标移到数字上面就有图标显示了
![image](https://user-images.githubusercontent.com/25629121/61260360-6c072100-a7b0-11e9-9b66-b13af6bd1d82.png)

**Comment by Vstory** [comment]
> 支持的，鼠标移到数字上面就有图标显示了
> ![image](https://user-images.githubusercontent.com/25629121/61260360-6c072100-a7b0-11e9-9b66-b13af6bd1d82.png)


原来如此
