### ISSUE TITLE
Star history shows "Request failed with status code 403"

### ISSUE THREAD

**Issue by huangyuzhang** [zenghongtu/Remu#18]
首先感谢一下作者，很不错的插件！

昨天装上的，今天前面还可以看history，刚刚没多久点了就出现 "Request failed with status code 403"。请问是不是 request 超过限制之类的？

**Comment by zenghongtu** [comment]
对得，GitHub 限制了每个小时只能请求接口60次，可以查看3-4个仓库star历史

**Comment by huangyuzhang** [comment]
好的，谢谢！

**Comment by zenghongtu** [comment]
> 首先感谢一下作者，很不错的插件！
> 
> 昨天装上的，今天前面还可以看history，刚刚没多久点了就出现 "Request failed with status code 403"。请问是不是 request 超过限制之类的？


昨天更新了一下，v1.0.5以上版本查询star history会加入使用token（如果填了的话），一个小时可以看约300个仓库
