### ISSUE TITLE
Tag 重复创建

### ISSUE THREAD

**Issue by Blankeer** [zenghongtu/Remu#2]
![image](https://user-images.githubusercontent.com/8948303/59320909-bfdea000-8d02-11e9-8959-d5dcfff6157e.png)

gist 文件：
![image](https://user-images.githubusercontent.com/8948303/59320938-d1c04300-8d02-11e9-96cd-eadbb5532f2b.png)

应该是判断添加的时候没有考虑重复？

**Comment by zenghongtu** [comment]
本来是要加的，后来给忘了。感谢提醒，等会加上😊
