### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hellodword** [zenghongtu/Remu#21]
很棒的插件，感谢！

我需要在 `/view-tab.html` 给近千个 `untagged stars` 添加 `Notes`（...），于是有几点关于 tags 的需求：

1. 在 Notes 里按 TAB 键等于创建 tag，但是如果有重复的就需要按一下 ↓ 键再按回车，希望增加判断：如果重复就直接使用已创建的 tag，否则就创建。

2. tag 能否大小写不敏感？（我不确定这个需求是否会干扰到其它人的需求，或许可以增加个设置项？）

同时有个小问题：

例如已存在 `#re` 这个 tag，然后再创建一个 `#RE`，然后可以将 `#RE`  重命名为 `#re` 并且不会有警告，但它们在 `remu-sync-data.json` 中对应的 id 是不同的。所以是否也可以考虑添加 `合并 tag` 的功能呢？也就是可以将 `#RE` 批量 `移动` 到 `#re` 下面。

**Comment by zenghongtu** [comment]
大小写敏感确实可以加个设置，晚上我加上。

后面那个小问题，你可以自己解决。直接修改 remu-sync-data.json，把 #RE 对应的数据移动到 #re 下面就可以了。

**Comment by hellodword** [comment]
很棒，感谢！

但是去掉了勾选 `Case Sensivivity`，Tags 列表的 Sort 和 Notes 的补全提示还是大小写敏感的

还有希望 `remu-sync-data.json` 中可以存一下这些设置选项，例如 Filter 勾选 Tags，或者 Tags 列表的 Sort By Alphabetical (A-Z)，刷新之后又要重新点击

**Comment by zenghongtu** [comment]
> 但是去掉了勾选 `Case Sensivivity`，Tags 列表的 Sort 和 Notes 的补全提示还是大小写敏感的

这个。。。晚上回去加上

> 还有希望 `remu-sync-data.json` 中可以存一下这些设置选项，例如 Filter 勾选 Tags，或者 Tags 列表的 Sort By Alphabetical (A-Z)，刷新之后又要重新点击

这个之前本来要做的，后来忘了😱。remu-sync-data.json 是存数据的，不对它做改动了，这个存到Chrome自带的同步数据里面就好了

**Comment by hellodword** [comment]
nice!!!

谢谢!
