### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by ZER0-Nu1L** [zenghongtu/Remu#28]
How to rename the current tage? I can't find such fuction.

**Comment by GeekaholicLin** [comment]
Hover the number after the tag name, and click the 'edit' icon on the tooltips.
After typing the name you want, use the Enter key in the keyboard to finish renaming.

![image](https://user-images.githubusercontent.com/13808849/69872541-9c2f0680-12f0-11ea-878a-7521e7914bb5.png)

**Comment by ZER0-Nu1L** [comment]
Thanks！
