### ISSUE TITLE
换浏览器所有标签都丢了

### ISSUE THREAD

**Issue by xxzj990** [zenghongtu/Remu#36]
gists同步其实意义不大。
试着手动修改gists，同步不下来...

**Comment by Soarkey** [comment]
手动改完gist，还需要自己在remu插件上设置一下update local选项才能生效，亲测成功

**Comment by xxzj990** [comment]
> 手动改完gist，还需要自己在remu插件上设置一下update local选项才能生效，亲测成功

目前正常了，谢谢~
