### ISSUE TITLE
关于功能需求的几点小见意

### ISSUE THREAD

**Issue by winder9090** [zenghongtu/Remu#7]
1.能否添加Tag组合查找功能，比如查找同时加了Java和Android标签的项目
2.能否添加备注功能，有些项目除了加Tag，还想项目功能描述的备注

**Comment by zenghongtu** [comment]
感谢提建议。

1. 这个功能可以实现，但是交互方面我暂时还没有想到要怎么做
2. 这个我今天早上也想到了，晚点把它实现了

**Comment by winder9090** [comment]
Tag组合查找功能，是不是可以参考The Fucking Github扩展相关做法

**Comment by winder9090** [comment]
> 感谢提建议。
> 
> 1. 这个功能可以实现，但是交互方面我暂时还没有想到要怎么做
> 2. 这个我今天早上也想到了，晚点把它实现了
Tag组合查找功能，是不是可以参照The Fucking Github扩展的做法

**Comment by winder9090** [comment]
Tag组合查找功能，是不是可以参考The Fucking Github扩展的做法

**Comment by zenghongtu** [comment]
搞定了，安装 `0.3.0`试试看
